apiVersion: v1
kind: Pod
metadata:
  name: log-generator
  labels:
    app: loggen
spec:
  containers:
  - name: log-gen-pod
    image: viveksaini2612/watermelon_log:latest
    ports:
    - containerPort: 8080
  restartPolicy: Never
